import React from "react";
import Layout from "../components/layout";
import HeaderTwo from "../components/header/header-two";
import StickyHeader from "../components/header/sticky-header";
import PageHeader from "../components/page-header";
import BrandCarousel from "../components/brand-carousel";
import { Container, Row, Col } from "react-bootstrap";
import Footer from "../components/footer";
import Head from "next/head";

const Forsaljningsvillkor = () => {
  return (
    <>
      <Head>
        <title>Forsaljningsvillkor</title>
        <meta name="title" content="Forsaljningsvillkor - GreenPlank.se" />
        <meta name="description" content="Läs det här dokumentet noggrant. Den innehåller viktig information om dina rättigheter och skyldigheter samt begränsningar och uteslutningar som gäller dig." />
      </Head>
      <Layout pageTitle="Försäljningsvillkor">
        <HeaderTwo />
        <PageHeader title="Försäljningsvillkor" crumbTitle="försäljningsvillkor" />
        <StickyHeader />
        <section className="about-one pt-120 pb-40">
          <Container>
            <Row style={{ marginBottom: "4em" }}>
              <Col lg={12}>
                <h2>Försäljningsvillkor</h2>
                <div className="mb-30">
                  <p>OBS! Läs detta dokumentet försiktigt i sin helhet. Det innehåller viktig information om era rättigheter och skyldigheter, även om begränsningar och undantag som gäller för er.</p>
                  <p className="mb-30 mt-30">Detta avtal innehåller de villkor som gäller för kunder för köp från Green Plank AB. (nedan kallad “Green Plank”) och Green Plank-enheten som anges på fakturan som kommer att tillhandahållas dig (Kunden) vid beställningar på sålda produkter. Kunden samtycker till att vara bunden av och accepterar detta avtal enligt vad som är tillämpligt på kundens köp av produkter från Green Plank och / eller Green Plank Internet-webbplats (nedan kallad “hemsidan”). Som ett villkor för försäljning samtycker kunden till vara bunden av och accepterar dessa villkor. Dessa villkor gäller (i) såvida inte kunden har undertecknat ett separat formellt köpeavtal med Green Plank, i vilket fall ska det separata avtalet gälla; eller (ii) såvida inte andra Green Plank-standard villkor gäller för transaktionen som anges här eller någon annanstans. Dessa villkor kan ändras utan föregående skriftligt meddelande när som helst, enligt Green Planks eget gottfinnande.</p>
                  <p className="mb-30 mt-30">Ert godkännande av dessa försäljningsvillkor inkluderas i ert godkännande av villkoren och användningen av denna hemsida .</p>
                  <h3 className="mb-30 mt-30"><strong>1. </strong>Godkännande av order</h3>
                  <p className="mb-30 mt-30">Kundens mottagande av en elektronisk eller annan form av order bekräftelse betyder inte att Green Plank accepterar kundens order, och det utgör inte heller någon bekräftelse på Green Planks erbjudande att sälja. Alla beställningar accepteras i Malmö, Sverige. Green Plank förbehåller sig rätten när som helst efter mottagandet av kundens beställning att acceptera eller avvisa Kundens beställning av rimliga skäl inklusive men inte begränsat till brist på tillgänglighet av produkter, Kundens underlåtenhet att uppfylla betalningsvillkor och / eller brott mot kunden i detta avtal. Om betalning har mottagits för köpet och Green Plank annullerar kundens beställning ska Green Plank genast utfärda en återbetalning som motsvarar det belopp som mottagits för den ej accepterade eller annullerade beställningen.</p>
                  <h3 className="mb-30 mt-30"><strong>2. </strong>Betalnings villkor</h3>
                  <p className="mb-30 mt-30">Betalningsvillkoren ligger inom Green Planks egen rätt eller gottfinnande och om inte annat godkänns av Green Plank, måste betalningen vara mottagen eller på annat sätt auktoriserad eller säkrad i en form som godkänts av Green Plank innan Green Plank accepterar en order. Betalning för produkterna sker med godkänt kreditkort, bank överföring, elektronisk överföring eller någon annan förutbestämd betalnings metod som Green Plank godkänner. Fakturor förfaller och betalas senast det eller de betalnings datum som anges via elektronisk (inklusive men inte begränsat till e-post), fax och/eller muntlig bekräftelse mellan Green Plank och kunden. Green Plank kan fakturera delar av en beställning separat. Beställningar är inte bindande för Green Plank förrän de godkänts av Green Plank (se Godkännande av order). Alla offerter från Green Plank är giltiga under den period som anges på offerten. Green Plank förbehåller sig rätten att justera eller annullera offert efter behov.</p>
                  <h3 className="mb-30 mt-30"><strong>3. </strong>Frakt</h3>
                  <p className="mb-30 mt-10">Kunden ansvarar för alla kostnader i samband med leverans av produkten till den plats som kunden anger. Det är kundens ansvar att tillhandahålla kontakt information som gör att avsändaren kan kontakta kunden när sändningen sker. Frakt priser gäller endast för standard hämtning och leverans. Kunden är ansvarig för att lossa varorna från transportören. Ytterligare lagrings- och / eller fraktkostnader och andra lager avgifter kan tillkomma om kunden inte kan kontaktas eller inte är tillgänglig för att ta emot produkten; eller om produkten omdirigeras på kundens begäran. Om ett frakt pris anges med felaktigt pris på grund av typografiska fel eller fel i pris information som erhållits från Green Planks leverantörer, har Green Plank rätt att vägra, justera eller annullera beställningar som gjorts oavsett om beställningen har gjorts eller inte bekräftat eller huruvida betalningen har återbetalats. Kunden ansvarar för att inspektera godset med avseende på brist eller tecken på skada vid mottagande av varor. Alla fordringar på frakt, förlust och skada måste lämnas in till Green Plank inom sju (7) arbetsdagar från den dag leveransen levererades. (se 10. Begränsningar av skador eller kontakta oss på: info@GreenPlank.eu.) Green Plank är inte ansvarig för fördröjning eller misslyckande i utförandet eller leverans eller av material eller varor eller för skador som lider av kund på grund av sådan försening eller misslyckande när sådan försening eller fel orsakas direkt eller indirekt av eller på något sätt härrör från eller är kopplat till handlingar från Gud, handlingar från offentliga fiender, upplopp, handlingar från statliga myndigheter, arbetes problem, misslyckande leverantörer att skicka eller producera varor, fördröjning av säkringen eller bristen på råvaror, nedbrytning eller förstörelse av anläggning eller utrustning, eller någon annan orsak eller som ligger utanför Green Planks kontroll, oavsett om de anges här. Alla beställningar anses avstängda så länge som en sådan orsak förhindrar eller fördröjer prestanda eller leverans.</p>
                  <h3 className="mb-30 mt-30"><strong>4. </strong>Skatt</h3>
                  <p className="mb-30 mt-10">Kunden ansvarar för all försäljning, användning, punktskatt, mervärde och andra avgifter som är förknippade med beställningen, oavsett hur de anges, inklusive eventuella tullar, avgifts avgifter eller andra destinations avgifter. Om tillämpligt visas en separat avgift för sådana artiklar på Green Planks faktura.</p>
                  <h3 className="mb-30 mt-30"><strong>5. </strong>Frakt skador</h3>
                  <p className="mb-30 mt-10">Kontrollera ert paket vid ankomst för skador. Om ni finner skador måste ni notera dem på fraktsedeln när du signerar för leveransen, eller om ingen signatur krävdes, kontakta åkeriet omedelbart. Om inga skador noteras på fraktsedeln kan Green Plank inte hållas ansvarig för några skador. När det har noterats på fraktsedeln och ni bestämmer att ni inte kan använda produkten, kontakta Green Plank via e-post eller telefon för att rapportera det skadade materialet. Om ni råkar acceptera en leverans och undertecknar inga skador och senare upptäcker att det verkligen finns skador måste du kontakta transportföretaget inom 48 timmar efter leverans för att rapportera det. Green Plank kan inte göra några anspråk å era vägnar efter femton (15) arbetsdagar från leveranstid punkten eller leverans försök.</p>
                  <h3 className="mb-30 mt-30"><strong>6. </strong>Avbryta beställning</h3>
                  <p className="mb-30 mt-10">Ni har rätt att avbryta beställningen när som helst inom 24 timmar från det att ni fick en order bekräftelse från Green Plank. Ni måste kontakta Green Plank via e-post eller telefon så snart som möjligt. Om ert köp redan har skickats måste ni ordna en retur, och ni kommer att vara ansvarig för fraktkostnader + 20% “åter upplagrings avgift”. Om köpet inte har skickats kan ni göra av bokning utan kostnad till er ursprungliga betalnings metod, exklusive transaktions avgifter.</p>
                  <p>Beställningar gjorda av återförsäljare eller grossister, special beställningar och anpassad design, färg, modell, storlek osv., Beställningar kan inte annulleras när de bekräftats av Green Plank..</p>
                  <h3 className="mb-30 mt-30"><strong>7. </strong>Returnering</h3>
                  <p className="mb-30 mt-10">Om ni ändrar er så kan ni returnera oanvända eller oöppnade varor inom sju (7) dagar efter leverans för återbetalning (tyvärr kan eventuella fraktkostnader inte återbetalas). Varorna måste returneras i nytt, oöppnat och oanvänt skick och innehålla allt original material som ingår i leveransen. På returer så tillkommer det en avgift på 20% av priset som en “Åter lagrings avgift”. Kontakta oss för ett retur varumärknings nummer (RMA) om du vill göra en retur. Ett RMA-nummer krävs för varje retur.</p>
                  <p>
                    Efter att er leverans har mottagits i vårt lager kommer det att inspekteras. Om varan returneras i nytt, oöppnat och oanvänt skick så kommer ni att få en återbetalning till det ursprungliga inköpspriset plus moms om det är tillämpligt i den ursprungliga betalnings metoden, minus 20% avlagrings avgift minus fraktkostnader inom fyra veckor efter att ni har skickat tillbaka beställningen till oss. Om returen är ett resultat av vårt fel, vänligen ange att på retur förpacknings blanketten kommer vi att utfärda en återbetalning till det ursprungliga inköpspriset plus moms om tillämpligt plus fraktkostnader i den ursprungliga betalnings metoden.</p>
                  <h3 className="mb-30 mt-30"><strong>8. </strong>Avslag</h3>
                  <p className="mb-30 mt-10">Om leveransen ej tas emot vid ankomst, är ni ansvarig för leverans- och retur frakt kostnader + 20% lager avgift. Eventuella skador från nekade leveranser återbetalas inte, och eftersom det vägrades skulle det inte noteras. Vi är inte ansvariga för NÅGRA kostnader i samband med en nekad leverans.</p>
                  <h3 className="mb-30 mt-30"><strong>9. </strong>Garantier</h3>
                  <p className="mb-30 mt-10">Alla garantier som anges är endast tillverkar- / produkt specifika garantier. Green Plank ger inga uttryckliga garantier förutom de som anges i detta avtal och i Green Planks tillämpliga garanti uttalande som gäller på faktura datumet. Sådana garantier kommer att vara effektiva och Green</p>
                  <p>
                    Plank är skyldig att respektera sådana garantier, endast efter att Green Plank mottagit full betalning för att varan ska garanteras. Innan ni returnerar en vara måste kunden kontakta Green Planks Skade avdelning. för ett garanti nummer (WA) inom den tillåtna perioden som anges av tillverkaren av produkten (se produkt specifik garanti). WA-numret är endast giltigt för den produkt som beskrivs där. Den returnerade produkten måste matcha den produkt som är godkänd för retur. Kunden måste se till att alla returer tas emot av tillverkaren / leverantören inom trettio (30) dagar från det att WA-numret erhållits. Alla leverans arrangemang för retur eller byte måste behandlas via Green Planks logistik avdelning. Kunden ansvarar för alla leverans- och hanterings avgifter för garanti returer, förutom där tillverkaren av produkten har gått med på att betala för sådana kostnader eller som beskrivs under produkt garantin. När det är möjligt eller enligt beskrivningen under garantin måste alla artiklar i nytt skick, i original förpackning och med alla garanti kort, manualer och tillbehör. Original paketet måste ingå och WA-numret syns på förpackningen. Green Plank kan kräva en kort skriftlig förklaring och ett fotografi eller en digital bild av den defekta produkten. I vissa fall krävs en inspektion på plats av produkten. Green Planks Skade avdelning kommer att informera kunden om detaljerna specifika för garanti anspråket.</p>
                  <p>
                    GARANTIERNA I DETTA AVTAL ÄR TILLVERKARE / PRODUKT SPECIFIKA GARANTIER FÖR PRODUKTEN (ER). GREEN PLANK FÖREDRAR UTTRYCKLIGA ÖVRIGA GARANTIER, GARANTIER ELLER UTFÖRANDE, VID UTTRYCKT, UNDER FÖRSTÄLL ELLER FÖRESKRIFTER, INKLUDERANDE UNDERFÖRSTÅDD GARANTI FÖR SÄLJBARHET ELLER FITNESS FÖR ETT SÄRSKILT SYFTE. GREEN PLANK FRISKRIVNING OCH ALLA UNDERFÖRSTÅDDA GARANTIER FÖR HANDELS ANVÄNDNING ELLER UTFÖR ETT KURS FÖR HANDLING ELLER UTFÖRANDE AV PRESTANDA. GREEN PLANK GARANTERAR INTE ATT PRODUKTEN ÄR FELFRI ELLER GARANTERAR ATT VARJE FEL KORRIGERAS. GREEN PLANK GARANTERAR INTE ATT ALLA PRODUKTER FÖLJER SPECIFIK GEOGRAFISK ÖVERENSSTÄMMELSE ELLER FÖRESKRIFTER. DET ÄR KUNDENS ANSVAR FÖR ATT SÄKRA ATT ANVÄNDNING AV KÖPTA PRODUKTER ÖVERENSSTÄMMER MED LOKALA JURISDIKTIONS KODER OCH MED ALLA REGIONALA, NATIONELLA OCH INTERNATIONELLA LAGAR OCH REGLER. GREEN PLANK FRÅN FRÅN FRÅGAR PATENT / INTELLEKTUELL FASTIGHETS RÄTTIGHETER, GARANTIER ELLER ERSÄTTNINGAR MED HÄNVISNING TILL NÅGOT LÅSNING / ANSLUTNINGS SYSTEM (ER) ANVÄNDA AV TILLVERKARE AV LAMINAT, ENGINEERAD TRÄ ELLER ANDRA PRODUKTER SÅLDA AV GREEN PLANK.</p>
                  <h3 className="mb-30 mt-30"><strong>10. </strong>BEGRÄNSNING AV SKADOR</h3>
                  <p className="mb-30 mt-10">GREEN PLANK ACCEPTERAR INTE ANSVAR UTANFÖR ÅTGÄRDERNA SOM HÄNVISAS HÄR. GREEN PLANK ÄR INTE ANSVARIG FÖR FÖRLORAD VINST, FÖRLORAD INKOMST ELLER AFFÄRS OMRÅDEN ELLER ANDRA FÖLJANDE, SPECIELLA, INDIREKTA ELLER PUNITIVA SKADOR, ÄVEN OM DE VAR FÖRSIKTIGA ELLER OM GREEN PLANK HAR RÅDS FÖR POTENTIAL AV SÅDAN SKADA, ELLER AV NÅGRA TREDJE PARTER FÖR UTTRYCKLIGT UTGÅENDE HÄR. KUNDEN GODKÄNNER ATT FÖR ALLA ANSVAR I HÄNVISNING AV INKÖP AV PRODUKTER ELLER TJÄNSTER, ÄR GREEN PLANK INTE ANSVARIG ELLER ANSVARIG FÖR NÅGON MÄNGD AV SKADOR OVAN DET VANLIGA BELOPPET BETALT AV KUNDEN FÖR KÖPEN I ENLIGHET MED DETTA. DENNA BEGRÄNSNING GÄLLER OCH UTFÖRANDE AV ÅTGÄRDEN (DVS HURUVIDA RÄTTSVÄSENDET ÄR I KONTRAKT ELLER I SKADESTÅND, INKLUSIVE FÖRSUMMELSE)..</p>
                  <h3 className="mb-30 mt-30"><strong>11. </strong>Gällande Lag</h3>
                  <p className="mb-30 mt-10">Detta avtal och dess utförande regleras av Sveriges lagar i alla frågor som uppstår från eller relaterar till användningen av denna webbplats, oavsett om det gäller anspråk i avtal, skadestånd eller på annat sätt, utan hänsyn till dess lag konflikter. Ni och Green Plank samtycker till att varje talan som kan uppkomma enligt detta avtal ska inledas och prövas vid lämplig domstol i Sverige, Skåne län. Du och Green Plank samtycker var och en till att underkasta sig den personliga och exklusiva behörigheten för domstolarna i Skåne i Sverige. Green Planks underlåtenhet att utöva eller genomdriva någon rättighet eller bestämmelse i användarvillkoren ska inte utgöra ett avstående från sådan rättighet eller bestämmelse. Om någon bestämmelse i användarvillkoren finner att en domstol med behörig jurisdiktion är ogiltig, är parterna ändå överens om att domstolen ska sträva efter att verkställa parternas avsikter som återspeglas i bestämmelsen och de andra bestämmelserna i villkoren. användningen förblir i full kraft och effekt. Du samtycker till att oavsett lag eller annan lag som motsätter dig, måste alla anspråk eller orsaker till handlingar som härrör från eller är relaterade till användning av Produkterna och tjänsterna eller användarvillkoren lämnas in inom en (1) månad efter ett sådant anspråk eller orsak till handling uppstod eller för alltid förbjuds.</p>
                  <h3 className="mb-30 mt-30"><strong>12. </strong>Övriga Dokument</h3>
                  <p className="mb-30 mt-10">Utöver vad som specifikt anges i något separat formellt köpeavtal mellan kunden och Green Plank, får dessa villkor INTE ändras, kompletteras eller ändras genom användning av andra dokument. Varje försök att ändra, komplettera eller ändra detta dokument eller att ange en beställning för produkter som omfattas av ytterligare eller ändrade villkor är ogiltiga, såvida inte annat avtalas i ett skriftligt avtal undertecknat av både kunden och Green Plank.</p>
                  <h3 className="mb-30 mt-30"><strong>13. </strong>Användnings villkor</h3>
                  <p className="mb-30 mt-10">Din tillgång till och användning av hemsidan regleras av Green Planks användarvillkor. Genom att använda den här webb platsen anger du att du accepterar utan att ändra dessa användarvillkor. Användarvillkoren kan komma att ändras utan föregående meddelande när som helst, enligt Green Planks eget gottfinnande, så du bör regelbundet läsa igenom användarvillkoren och tillämpliga policy för att förstå de villkor som gäller för din användning av platsen. I händelse av inkonsekvens mellan detta avtal och användnings villkoren gäller villkoren i detta avtal.</p>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
        <BrandCarousel />
        <Footer />
      </Layout>
    </>
  );
};

export default Forsaljningsvillkor;
